name: test @nomicon/types

on:
  push:
    paths:
      - '.github/workflows/types--*.yaml'
      - 'packages/types/**'
  pull_request:
    paths:
      - '.github/workflows/types--*.yaml'
      - 'packages/types/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['18', '20']
        ts:
          - '5.2'
          - '5.3'
          - '5.4'
          - 'next'
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^6.10.0
      
      - name: use node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: install ts ${{ matrix.ts }}
        working-directory: ./packages/types
        run: pnpm add typescript@${{ matrix.ts }}

      - name: test types
        run: pnpm test --dir packages/types